const ACTION_TYPES = {
  REST_LOADING: "REST_LOADING",
  REST_ERROR: "REST_ERROR",
  REST_SUCCESS: "REST_SUCCESS",

  BASKET_LOADING: "BASKET_LOADING",
  BASKET_ERROR: "BASKET_ERROR",
  BASKET_SUCCESS: "BASKET_SUCCESS",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  CLEAR_BASKET: "CLEAR_BASKET",
  UPDATE_BASKET: "UPDATE_BASKET",
};

export default ACTION_TYPES;
